### ISSUE TITLE
Cutadapt version

### ISSUE THREAD

**Issue by Citteny** [jdidion/atropos#121]
Hi there :)
In the readme it's written that 
` It is a fork of the venerable Cutadapt read trimmer`

From the issues that are open it looks like it is not using the latest 2.10 cutadapt.
Which Cutadapt version is currently used?
Thanks~!

**Comment by jdidion** [comment]
Atropos was forked from Cutadapt 1.10. Several of the features now available in Cutadapt (such as multicore) were first introduced in Atropos. Likewise, Cutadapt has added several features since 1.10 that are not in Atropos, but I try to port over the most important ones.

I've added a note about this in the README.
